- name: 'scope: CI/CD'
  color: '1D76DB'
  description: 'A change to the GitHub workflows'
- name: 'scope: core'
  color: '0E8A16'
  description: 'A change to the source code'
- name: 'scope: dependencies'
  color: '1D76DB'
  description: 'Pull requests that update dependencies'
- name: 'scope: documentation'
  color: '0075ca'
  description: 'Improvements or additions to documentation'
- name: 'scope: other'
  color: 'BFD4F2'
  description: 'No specific change type'
- name: 'status: help wanted'
  color: '008672'
  description: 'Extra attention is needed'
- name: 'status: stalled'
  color: 'FBCA04'
  description: 'Not planned to be merged yet'
- name: 'status: wontfix'
  color: 'ffffff'
  description: 'This will not be worked on'
- name: 'type: bug'
  color: 'd73a4a'
  description: "An issue that reports anything that isn't working as expected, or a pull request that fixes it"
- name: 'type: duplicate'
  color: 'e4e669'
  description: 'This issue or pull request already exists'
- name: 'type: enhancement/refactor'
  color: 'a2eeef'
  description: 'New feature or request'
- name: 'type: good first issue'
  color: '7057ff'
  description: 'Good for newcomers'
- name: 'type: invalid'
  color: 'e4e669'
  description: "This doesn't seem right"
- name: 'type: question'
  color: 'd876e3'
  description: 'Further information is requested'
- name: 'type: revert'
  color: 'E99695'
  description: 'Reverts a previous commit'
- name: 'type: vulnerability'
  color: 'B60205'
  description: 'Addresses a security vulnerability'
